name: "gradle"

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - run: mkdir staging && cp app/build/libs/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
